---
- name: Loop through DevOps tools
  hosts: localhost
  connection: local
  vars:
    devops_tools:
      - Ansible
      - Docker
      - Kubernetes
      - Jenkins
      - Terraform
  tasks:
    - name: Print DevOps tools
      debug:
        msg: 'DevOps tool: {{ item }}'
      loop: "{{ devops_tools }}"